
name: fullstack-identity-dev

services:

  host-api:
    pull_policy: build
    build:
      context: ..
      dockerfile: src/Sandbox.FullStackIdentity.Services.HostApi/Dockerfile
      target: final
      secrets: &build-secrets
        - GITHUB_USERNAME
        - GITHUB_TOKEN
    secrets: *build-secrets
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - target: 8080
        published: ${API_DEV_PORT:-8080}

  worker:
    pull_policy: build
    build:
      context: ..
      dockerfile: src/Sandbox.FullStackIdentity.Services.Worker/Dockerfile
      target: final
      secrets: *build-secrets
    secrets: *build-secrets
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      
  migrator:
    pull_policy: build
    build:
      context: ..
      dockerfile: src/Sandbox.FullStackIdentity.Services.Migrator/Dockerfile
      target: final
      secrets: *build-secrets
    secrets: *build-secrets
    environment: 
      - DOTNET_ENVIRONMENT=Development
            
  redis:
    ports:
      - target: 6379
        published: ${REDIS_DEV_PORT:-6379}
      
        
secrets:
  GITHUB_USERNAME:
    file: ./secrets/GITHUB_USERNAME.txt
  GITHUB_TOKEN:
    file: ./secrets/GITHUB_TOKEN.txt
  POSTGRES_USER:
    file: ./secrets/POSTGRES_USER.txt
  POSTGRES_PASSWORD:
    file: ./secrets/POSTGRES_PASSWORD.txt
  JWT_SIGNING_KEY:
    file: ./secrets/JWT_SIGNING_KEY.txt
  SENDGRID_API_KEY:
    file: ./secrets/SENDGRID_API_KEY.txt
  SENDGRID_VERIFICATION_KEY:
    file: ./secrets/SENDGRID_VERIFICATION_KEY.txt
