
name: fullstack-identity

services:

  host-api:
    pull_policy: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  worker:
    pull_policy: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
            
  migrator:
    pull_policy: always
    environment: 
      - DOTNET_ENVIRONMENT=Production


secrets:
  POSTGRES_USER:
    environment: "POSTGRES_USER"
  POSTGRES_PASSWORD:
    environment: "POSTGRES_PASSWORD"
  JWT_SIGNING_KEY:
    environment: "JWT_SIGNING_KEY"
  SENDGRID_API_KEY:
    environment: "SENDGRID_API_KEY"
  SENDGRID_VERIFICATION_KEY:
    environment: "SENDGRID_VERIFICATION_KEY"
