
services:

  host-api:
    build:
      context: ..
      dockerfile: src/Sandbox.FullStackIdentity.Services.HostApi/Dockerfile
      target: final

  worker:
    build:
      context: ..
      dockerfile: src/Sandbox.FullStackIdentity.Services.Worker/Dockerfile
      target: final

  migrator:
    build:
      context: ..
      dockerfile: src/Sandbox.FullStackIdentity.Services.Migrator/Dockerfile
      target: final
    